"""updated user model

Revision ID: 57e0d7150993
Revises: 110700a531eb
Create Date: 2018-07-26 18:22:13.088728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e0d7150993'
down_revision = '110700a531eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_active')
    # ### end Alembic commands ###
